config/routes.rb
Rails.application.routes.draw do

root 'sessions#home'

get '/login' => 'sessions#new', as: 'login'
get '/logout' => 'sessions#logout', as: 'logout'
get '/search' => 'places#search', as: 'search'
get '/home'   =>  'sessions#home', as: 'home'
get '/register' => 'users#new', as: 'register'
get '/profile' => 'users#profile', as: 'profile'

resources :responses, only: [:new, :create, :edit, :update, :destroy]
resources :sessions, only: [:create]
resources :cities, only: [:create, :update]
resources :users, only: [:create, :update, :destroy]
resources :places, only: [:new, :create, :update, :show]

end

app/models/place.rb
require 'csv'
class Place < ActiveRecord::Base
  # Associations
  belongs_to :city
  belongs_to :place_type
  has_many :responses
  has_and_belongs_to_many :categories

  # Validations
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :city_id
  validates :city_id, presence: true,
            numericality: { only_integer: true }

  # Scopes
  scope :places_by_city, -> (city) {
    joins(:city).where('city_id = ?', city.id )
  }

  scope :places_user_has_rated, -> (user) {
    joins(:responses).where('user_id = ?', user.id)
  }


  # Methods

  def place_rating(user)
    place = user.responses.find_by("place_id = ?", self.id)
    place.response
  end

  def response_id(user)
    r = user.responses.find_by("place_id = ?", self.id)
    r.id
  end

  def self.write_csv
    collection = self.all
    header = ["response","question","question_id","place_id","user_id","cat_or_ord"]
    file = "#{Rails.root}/lib/recommender/slim_response_data.csv"

    CSV.open(file, "w") do |writer|
      writer << header
      collection.each do |place|
        if place.id != 1
          u_responses = place.responses
          u_responses.each do |r|
            q = Question.find(r.question_id)
            if q.question == "Overall"
              writer << [r.response, q.question, r.question_id, r.place_id, r.user_id, q.cat_or_ord]
            end
          end
        end
      end
    end
  end

  def self.write_S3
    file = "#{Rails.root}/lib/recommender/slim_response_data.csv"
    s3 = AWS::S3.new
    bucket = s3.buckets['niche-travel']
    obj = bucket.objects['user_recs.csv']

    obj.write(Pathname.new(file))
  end

end

app/models/place_type.rb
class PlaceType < ActiveRecord::Base
  # Associations
  has_many :places
end

app/controllers/places_controller.rb
require 'yelp_client'

class PlacesController < ApplicationController
  before_action :current_user, :authorize

  def new
    @place = Place.new
    @place_types = PlaceType.where('id > 1')
    @response = Response.new
  end

  def search
    city     = City.find_by(name: params[:city][:city])

    recs = @current_user.user_recommendations.where('city_id = ?', city.id)
    places = get_places(recs)
    @response = call_yelp(places, city)
  end

  def create
    city          = City.find_by(name: params[:place][:city])
    place         = Place.new(place_params)
    place.city_id = city.id
    place.save!

    response             = Response.new
    response.response    = params[:response]
    response.place_id    = place.id
    response.user_id     = @current_user.id
    response.question_id = params[:question_id]
    response.save!

    redirect_to home_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :city_id, :categories)
  end

  def response_params
    params.require(:response).permit(:response, :place_id, :user_id, :question_id)
  end

  def get_places(recommendations)
    recommendations.map do |rec|
      Place.find(rec.place_id)
    end
  end

  def call_yelp(collection, city)
    all = []
    collection.each do |place|
      params = {term: place.name,
                limit: 2}
      resp  = Yelp.client.search(city.name, params) # method call to client
      regex = /biz\/(\S*)/
      biz   = regex.match(resp.businesses[0].url)
      final_resp = Yelp.client.business(biz[1]) # method call to client

      all.push([final_resp] + [{place: place.name}])
    end
    format_data(all)
  end

  def format_data(response)
    final_format = []
    response.each do |place|
      place2 = Place.find_by('name LIKE ?', place[1][:place])
      rec    = current_user.user_recommendations.find_by('place_id = ?', place2.id)
      img    = place[0].business.image_url.gsub!('/ms.jpg', '/l.jpg')
      img    = img.gsub!('http:', 'https:')

      final_format.push(
        {
          rank: rec.rank,
          score: rec.score,
          name: place[0].business.name,
          url: place[0].business.url,
          image_url: img,
          location: place[0].business.location.display_address
        })
    end
    return final_format
  end

end

app/views/places/new.html.erb
<div class="new-place col-lg-8 col-lg-offset-2">
  <%= form_for @place, url: places_path, html: {class: "form form-responsive"} do |f| %>

    <fieldset>
      <legend>Place Details</legend>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= select_tag 'Place Type', options_for_select(
          @place_types.collect{ |u| [u.description, u.id] }),
          options = { prompt: "Select a Place Type" } %>
      </div>

      <div class="form-group">
        <%= label_tag(:response, "1") %>
        <%= radio_button_tag(:response, "1") %>
        <%= label_tag(:response, "2") %>
        <%= radio_button_tag(:response, "2") %>
        <%= label_tag(:response, "3") %>
        <%= radio_button_tag(:response, "3") %>
        <%= label_tag(:response, "4") %>
        <%= radio_button_tag(:response, "4") %>
        <%= label_tag(:response, "5") %>
        <%= radio_button_tag(:response, "5") %>
        <%= hidden_field_tag(:question_id, 28) %>
      </div>
    </fieldset>

    <%= f.submit "Add Place", class: "btn btn-default" %>
  <% end %>
</div>

app/views/places/search.html.erb
<h3 id="class-recs">Recommendations for You</h3>
<div id="wrapper">
  <div id="columns">
    <% @response.each do |place| %>
    <div class="tile">
        <%= image_tag(place[:image_url]) %>
        <ul>
          <li class="place-name">
            <%= place[:name] %>
          </li>
          <li id="yelp">
            View on Yelp <%= link_to (place[:url]), popup: :true do %>
              <span class="glyphicon glyphicon-link"></span>
            <% end %>
          </li>
        </ul>
    </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$('a[popup]').on('click', function(e) {
    e.preventDefault();
    var newWindow = window.open($(this).attr('href'),'onYelp', 'height=900,width=700');
    newWindow.moveTo(50,50)
});
</script>