config/routes.rb
Rails.application.routes.draw do

root 'sessions#home'

get '/login' => 'sessions#new', as: 'login'
get '/logout' => 'sessions#logout', as: 'logout'
get '/search' => 'places#search', as: 'search'
get '/home'   =>  'sessions#home', as: 'home'
get '/register' => 'users#new', as: 'register'
get '/profile' => 'users#profile', as: 'profile'

resources :responses, only: [:new, :create, :edit, :update, :destroy]
resources :sessions, only: [:create]
resources :cities, only: [:create, :update]
resources :users, only: [:create, :update, :destroy]
resources :places, only: [:new, :create, :update, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Niche</title>
   <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lobster">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default small-header">
    <a href="/" id="logo" class="pull-left">Niche</a>
    <h5 class="greet pull-left"></h5>
    <% if session[:user_id] %>
      <div class="dropdown">
        <button class="btn btn-default dropdown pull-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Your things
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
          <li><%= link_to "View your profile", (profile_path) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Add Places", (new_place_path) %></li>
          <li><%= link_to "Rate Places", (new_response_path) %></li>
        </ul>
      </div>
    <h5 class="logout pull-right"><%= link_to "Logout", (logout_path) %></h5>
  </div>
  <% end %>
  <%= yield %>


</body>
</html>

app/views/layouts/modal.html.erb
<div id="inner-response-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      </div>
        <div class="modal-body">
          <ul class="errors"></ul>
        </div>
        <%= form_tag("/", method: :patch) do %>
          <div class="form-group">
            <%= label_tag(:response, "1") %>
            <%= radio_button_tag(:response, "1") %>
            <%= label_tag(:response, "2") %>
            <%= radio_button_tag(:response, "2") %>
            <%= label_tag(:response, "3") %>
            <%= radio_button_tag(:response, "3") %>
            <%= label_tag(:response, "4") %>
            <%= radio_button_tag(:response, "4") %>
            <%= label_tag(:response, "5") %>
            <%= radio_button_tag(:response, "5") %>
            <%= hidden_field_tag(:question_id, 28) %>
          </div>
          <div class="modal-footer">
            <%= submit_tag "Submit", class: "btn btn-primary" %>
            <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
          </div>
        <% end %>
    </div>
  </div>
</div>